main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('<single_slug>', views.single_slug, name='single_slug')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
        path('admin/', admin.site.urls),
        path('tinymce/', include('tinymce.urls')),
        path('', include('main.urls', namespace='main')),
    ]

main/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class TutorialCategory(models.Model):
    tutorial_cat = models.CharField(max_length=255)
    cat_summary = models.CharField(max_length=200)
    cat_slug = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.tutorial_cat


class TutorialSeries(models.Model):
    tutorial_series = models.CharField(max_length=200)

    tutorial_cat = models.ForeignKey(TutorialCategory,
                                     default=1,
                                     verbose_name='Category',
                                     on_delete=models.SET_DEFAULT
                                     )  # This is where we link them together
    series_summary = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Series'

    def __str__(self):
        return self.tutorial_series


class Tutorial(models.Model):  # First class created
    # TODO: Define fields here

    title = models.CharField(max_length=200)
    content = models.TextField()
    published = models.DateTimeField('Date Field', default=datetime.now())

    tutorial_seires = models.ForeignKey(TutorialSeries, default=1,
                                        verbose_name='Series',
                                        on_delete=models.SET_DEFAULT)
    tutorial_slug = models.CharField(max_length=200, default=1)

    class Meta:
        verbose_name = 'Tutorial'
        verbose_name_plural = 'Tutorials'

    def __unicode__(self):
        pass

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    # To modify the original method
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data.get('email')
        if commit:
            user.save()
        return user

main/views.py
from django.shortcuts import render, redirect
from .models import Tutorial, TutorialCategory, TutorialSeries
from .forms import NewUserForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.http import  HttpResponse
# Create your views here.


def single_slug(request, single_slug):

    cat = [c.cat_slug for c in TutorialCategory.objects.all()]
    if single_slug in cat:
        # from models.py we look and get what connected with ForignKeys
        matching_series = TutorialSeries.objects.filter(tutorial_cat__cat_slug=single_slug)
        series_urls = {}
        for m in matching_series.all():
            part_one = Tutorial.objects.filter(tutorial_seires__tutorial_series=m.tutorial_series).earliest('published')
            series_urls[m] = part_one.tutorial_slug
        return render(request, 'main/category.html', {'part_one': series_urls})

    tutorial = [t.tutorial_slug for t in Tutorial.objects.all()]
    if single_slug in tutorial:
        this_tutorial = Tutorial.objects.get(tutorial_slug=single_slug)
        # tutorial_from_series = Tutorial.objects.filter(tutorial_seires__tutorial_seires=this_tutorial.tutorial_seires).order_by('published')
        # this_tutorial_idx = list(tutorial_from_series).index(this_tutorial)
        return render(request, 'main/tutorial.html',
                      {'tutorial': this_tutorial,
                       # 'sidebar': tutorial_from_series,
                       # 'this_tutorial_idx': this_tutorial_idx
                       }
                      )

    return HttpResponse('This doesn\'t exist {}'.format(single_slug))


def homepage(request):

    category = TutorialCategory.objects.all()
    context = {
        'category': category
    }
    return render(request, 'main/categories.html', context=context)


def register(request):

    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            username = form.cleaned_data.get('username')
            messages.success(request, 'New user {} has been created.'.format(username))
            return redirect('main:home')
        else:
            for msg in form.error_messages:
                messages.error(request, form.error_messages[msg])

    form = NewUserForm
    return render(request, 'register.html', context={'form': form})


def logout_request(request):
    logout(request)
    messages.info(request, 'You are logged out successfully!!')
    return redirect('main:home')


def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'You are now logged in as {} .'.format(username.upper()))
                return redirect('main:home')
        else:
            messages.error(request, 'Invalid username or password!')

    form = AuthenticationForm()
    return render(request, 'login.html', context={'form': form})

main/templates/main/categories.html
{% extends 'index.html' %}



{% block content %}

    <div class="row">
        {% for cat in category %}
        <div class="col s12 m6 l4">
          <div class="card blue-grey darken-1">
            <a href="{{cat.cat_slug}}">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="card-title">{{ cat.tutorial_cat }}</div>
                        <hr />
                        <p>{{ cat.cat_summary }}</p>
                    </div>
                </div>
            </a>
          </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

main/templates/main/category.html
{% extends 'index.html' %}



{% block content %}

    <div class="row justify-content-center">
        {% for tut, partone in part_one.items%}
        <div class="col s12 m6 l4 ">
          <div class="card blue-grey darken-1">
            <a href="{{partone}}">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="card-title">{{ tut.tutorial_series }}</div>
                        <hr />
                        <p>{{ tut.series_summary }}</p>
                    </div>
                </div>
            </a>
          </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

main/templates/main/mainhome.html
{% extends 'index.html' %}



{% block content %}

    <div class="row">
        {% for title in category %}
        <div class="col s12 m6 l4">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title">{{ title.title }}</span>
                <p style="font-size:70%">{{ title.published }}</p>
                <hr />
                <p>{{ title.content }}</p>
            </div>
            <div class="card-action">
              <a href="#">Read more</a>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

main/templates/main/tutorial.html
{% extends 'index.html' %}



{% block content %}

    <div class="row">
        <div class="col s12 m8 l8">
            <h3>{{tutorial.title}}</h3>
            <p style="font-size:70%">Published {{ tutorial.published }}</p>
            {{tutorial.content|safe}}
        </div>
        <div class="col s12 m8 14">
            <ul class="collapsible popout">
                {% for tutorial in sidebar %}
                    {% if forloop.counter0 == this_tutorial_idx %}
                        <li class="active">
                            <div class="collapsible-header">{{tutorial.title}}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{tutorial.title}}</div>
                            <div class="collapsible-body">
                                <a href="/{{tutorial.tutorial_slug}}">
                                    <button class="btn waves-effect waves-light right-align" style="backgound-color:yellow; color:black">
                                        Go
                                    </button>
                                </a>
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

    </div>

{% endblock %}

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script> M.toast({html: '{{ message }}', classes:'green rounded', displayLength:2000});</script>
        {% elif message.tags == 'error' %}
            <script> M.toast({html: '{{ message }}', classes:'red rounded', displayLength:10000});</script>
        {% else %}
            <script> M.toast({html: '{{ message }}', classes:'blue rounded', displayLength:2000});</script>
        {% endif %}
    {% endfor %}
{% endif %}

templates/includes/nav.html
<nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo" style="padding-left:2%">Tutorials!!</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">

          {% if user.is_authenticated %}
            <li style="margin-left: -35%;"><a href="#">{{ user.username.capitalize }} </a></li>
            <li style="margin-right: 32%;"><a href="{% url 'main:logout' %}">Logout</a></li>
          {% else %}
            <li style="margin-left: -35%;"><a href="{% url 'main:register' %}">Register</a><li>
            <li style="margin-right: 32%;"><a href="{% url 'main:login' %}">Login</a><li>
          {% endif %}

          <li><a href="http://127.0.0.1:8000/admin/">Admin</a></li>
      </ul>
    </div>
</nav>

templates/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Site</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet" />

</head>

<body>
    <header>
        {% include 'includes\nav.html' %}
    </header>



    <div class="container">
        <br>
        {% block content %}{% endblock %}
    </div>


    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'tinymce/js/prism.js' %}"></script>
    <script>M.AutoInit();</script>
    {% include 'includes\messages.html' %}

</body>

</html>

templates/login.html
{% extends 'index.html' %}



{% block content %}

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <button class='btn' type="submit">Submit</button>
    </form>

    if you don't have an account, <a href="{% url 'main:register' %}" style="font-weight:bold">Register</a> instead.
{% endblock %}

templates/register.html
{% extends 'index.html' %}



{% block content %}

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <button class='btn' type="submit">Submit</button>
    </form>

    if you already have an account, <a href="login/" style="font-weight:bold">Login</a> instead.
{% endblock %}